name: flutter_cef
description: Flutter Desktop Webview backed by CEF (Chromium Embedded Framework).
version: 0.2.2
homepage: https://github.com/ozayakcan/flutter_cef
repository: https://github.com/ozayakcan/flutter_cef

environment:
  sdk: ">=2.17.1 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: FlutterCefPlugin
      windows:
        pluginClass: FlutterCefPluginCApi
      linux:
        pluginClass: FlutterCefPlugin
